schema: "./src/services/network/models/schema.graphql"
documents:
  - "./src/**/*.graphql"
generates:
  ./generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo